export { default as HeroBanner } from "./HeroBanner";
export { default as MobileAppSection } from "./MobileAppSection";
export { default as ProfessionsSection } from "./ProfessionsSection";
export { default as JobsSection } from "./JobsSection";
export { default as HomeJobsSection } from "./HomeJobsSection";
export { default as WelcomeSectionNew } from "./WelcomeSectionNew";
export { default as TalentsSection } from "./TalentsSection";
export { default as PartnersSection } from "./PartnersSection";
export { default as TwinsSection } from "./TwinsSection";
